# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_modular_headers!

target 'MyInsight_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyInsight_Swift
  pod 'Alamofire' # 网络请求工具
  pod 'AFNetworking', '~> 3.0'
  pod 'SnapKit'   # 代码约束布局
  # pod 'MMDrawerController' # 抽屉 swift写的
  pod 'RealmSwift'
  pod 'SQLite.swift' # Swift下SQLite数据库
  # 侧边demo MLSideslipView
  # 侧边demo DrawerViewController
  #pod 'DKChainableAnimationKit' # 动画
  pod 'WeexSDK'
  pod 'CryptoSwift'
  
  # OC
  pod 'SSZipArchive' # 解压缩zip文件
  pod 'SWRevealViewController'
  
  # 数据库
  #
  pod 'GRDB.swift'
  ### 画图工具 Sketch
  
  # PDF
  pod 'ILPDFKit'
  
  
  # MarkDown
#  pod 'MarkdownView'
  #pod 'EFMarkdown' # 编译不通过 先注释掉

  target 'MyInsight_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyInsight_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
