# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# 工程
target 'FilesClippers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FilesClippers

end

# 第三方库
target 'LLBlueTooth' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LLBlueTooth

end
